# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Runs the pipeline when new code is pushed to the 'main' branch

pool:
  vmImage: 'windows-latest'  # Use a Windows agent

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Change this to match your .NET version
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet restore "$(Build.SourcesDirectory)/Manoj/MyWebApp/MyWebApp.csproj"
  displayName: 'Restore Dependencies'

- script: dotnet build "$(Build.SourcesDirectory)/Manoj/MyWebApp/MyWebApp.csproj" --configuration Release
  displayName: 'Build Solution'

- script: dotnet publish "$(Build.SourcesDirectory)/Manoj/MyWebApp/MyWebApp.csproj" -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish Application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish Artifact'



